version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/somnium-server

permissions:
  - object: /home/ec2-user/somnium-server/
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 60
      runas: root