name: Java CD with Amazon EC2, S3, Code Deploy

on:
  push:
    branches: [ master, develop, feature/github-action-ci-cd ]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create application.yml
        run: |
          mkdir ./src/main/resources
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml

      - name: Create application-test.yml
        run: |
          mkdir ./src/test/resources
          touch ./src/test/resources/application.yml
          echo "${{ secrets.APPLICATION_TEST_YML }}" >> ./src/test/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://somnium-bucket/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name somnium-code-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name staging --s3-location bucket=somnium-bucket,bundleType=zip,key=somnium-bucket/$GITHUB_SHA.zip

      - name: Somnium Server CD Success Alarm
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ Somnium Server CD Success 💭
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 00FF00

      - name: Somnium Server CD Failure Alarm
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❌ Somnium Server CD Failure 💭
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: FF0000